### ISSUE TITLE
Have you train the model on one database and test  it on another database?

### ISSUE THREAD

**Issue by wuqiangch** [google/uis-rnn#24]
In your paper, "We randomly partition the dataset into five subsets, and each time leave one subset for evaluation, and train UIS-RNN on the other four subsets. Then we combine the evaluation on five subsets and report the averaged DER." So the persons in  traindatas  also appeare in the testdata.
Have you train the model on one database and test  the model on another database? The persons in  traindatas  dont  appeare in the testdata.
I have done it ,but get the bad result.

**Comment by wq2012** [comment]
Yes, we do have these results, as presented in Table 2.

You might be looking at an old version of the paper.

![screenshot from 2019-01-08 10-34-15](https://user-images.githubusercontent.com/3002724/50840702-2107df00-1331-11e9-9ae6-d50ed30616d4.png)

**Comment by Aurora11111** [comment]
@wuqiangch I have tested this project with my own datsets too,but get really bad result when I  test my model on database which persons in traindatas dont appeare in the testdata.

**Comment by wq2012** [comment]
@Aurora11111 Although our training of UIS-RNN is on a different domain than the test set in above highlighted experiments, our training of the speaker embedding model is based on a super large dataset covering 100K+ speakers, and from various microphones and acoustic environments.

If your cross-domain results are bad, very likely it's because your speaker embedding model is too weak, which is unrelated to the UIS-RNN model.
