### ISSUE TITLE
The clustering performance influenced by overlap window size

### ISSUE THREAD

**Issue by taylorlu** [google/uis-rnn#41]
@wq2012 
The overlap rate seems strongly influenced the number of speakers.
Since when overlap size is larger, the speaker embedding will change more smoothly, and the change points will hard to detect, it's apt to generate fewer speakers.
And the size of sliding window also affects a lot, although this problem is caused by the speaker embedding algorithm.
This is my project integrates with the vgg-speaker-recognition algorithm: [Speaker-Diarization](https://github.com/taylorlu/Speaker-Diarization)
Thanks a lot.

**Comment by wq2012** [comment]
For the window size, please make sure you train the speaker embedding model using **variable-length windows**.

In section 4.5 of our [paper](https://arxiv.org/pdf/1810.04719.pdf), we have stated that variable-length windows for speaker embedding training is essential for good diarization performance.

About the overlap, if you use exactly **the same** overlap for UIS-RNN training and evaluation, it won't be a problem. Since the smoothness information is going to be learned into the UIS-RNN model.

**Comment by ldeseynes** [comment]
Hi @wq2012,

In the section 4.1 of your [paper](https://arxiv.org/pdf/1810.04719.pdf) you you say you've retrained a new d-vector model V3 using variable-length windows using sizes within [240ms,1600ms]. Since the window size for the diarization system is 240ms, why didn't you choose the same size for the d-vector model ? Is it because the training was inefficient with fixed-length windows of such a small size ?

Thanks in advance

**Comment by wq2012** [comment]
@ldeseynes Hi, it's simply because we use the same model for different applications. For diarization, the window size is 240ms. For other applications like recognition, the window size can be as large as 1.6s.

You can of course only train the model with 240ms windows, but that limits the usefulness of the model.

**Comment by hbredin** [comment]
I believe @ldeseynes has a point here.

It is not clear whether the performance improvement comes from training on variable length windows or on shorter windows. The paper seems to suggest the former, while you seem to suggest the latter.

Would be nice to see how a model trained on fixed-length 240ms windows only would reach the same performance.

**Comment by wq2012** [comment]
@hbredin I see. Thanks for pointing it out.

What we really want to suggest is actually training with **consistent** window length as inference logic, not necessarily variable-length. Indeed we don't have experiments to show the diarization performance when speaker embedding model is trained only with 240ms windows. I will see if the team has some extra circles to add such experiments.

**Comment by taylorlu** [comment]
It confused me that could I generate speaker embedding **(fixed model)** by using variable length windows instead of **retraining** the speaker embedding module for more robust.  Since the former is cheaper.

**Comment by wq2012** [comment]
@taylorlu You can do both, since both are **consistent with inference**.

What we did is developing one model with variable length windows, and use it for both diarization (240ms windows) and other applications (larger windows). And the reason is exactly what you said - it's cheaper.

Only thing you should avoid is to use a window size for inference that has never been used in training.

Sorry for the confusions. Let me know if it's clear to you now.
